---
services:
  server:
    image: "ghcr.io/max298/starrupture-docker:main"
    volumes:
      - "./data:/server/gamedata"
    ports:
      - "7777:7777"
      # port 30020 holds a websocket by unreal engine, which allows to control the server (?)
      # https://dev.epicgames.com/documentation/en-us/unreal-engine/remote-control-api-websocket-reference-for-unreal-engine
      #- "30020:30020/tcp"
...
